# Generated by Django 3.2.16 on 2022-10-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='food_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'rice'), (2, 'bread and rotis'), (3, 'meat'), (4, 'fish'), (5, 'drinks'), (6, 'sweet'), (6, 'seafood')], null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='meal_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'starter'), (2, 'main'), (3, 'dessert')], null=True),
        ),
    ]
