# Generated by Django 3.2.16 on 2022-10-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('number_of_persons', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('date', models.DateField()),
                ('time', models.PositiveSmallIntegerField(choices=[(1, '11:00-12:00'), (2, '12:00-13:00'), (3, '13:00-14:00'), (4, '14:00-15:00'), (5, '16:00-17:00'), (6, '18:00-19:00'), (7, '20:00-21:00')], null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
