# Generated by Django 3.2.18 on 2023-03-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_remove_reservation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='number_of_persons',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True),
            
        ),
    ]
