# Generated by Django 3.2.18 on 2023-03-08 14:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_alter_reservation_ref_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='ref_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
