# Generated by Django 3.2.18 on 2023-03-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_alter_reservation_ref_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='ref_number',
            field=models.UUIDField(editable=False, unique=True),
        ),
    ]
